FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY tsconfig.json ./
COPY drizzle.config.ts ./
COPY src ./src

RUN npm run build
RUN npm prune --omit=dev

EXPOSE 8080

CMD ["npm", "run", "start"]
